apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: CONFIG_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: gateway-service-secrets
                  key: CONFIG_SERVER_URL
            - name: VAULT_URI
              valueFrom:
                secretKeyRef:
                  name: gateway-service-secrets
                  key: VAULT_URI
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gateway-service-secrets
                  key: VAULT_TOKEN
