name: gateway-service

replicaCount: 1

image:
  repository: 879381276515.dkr.ecr.ap-northeast-2.amazonaws.com/aigongbu/service-images
  tag: 1c12dd2b6bed62fd32f2af96844313db7bfccf88
  pullPolicy: IfNotPresent

containerPort: 80

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 384Mi

service:
  type: ClusterIP
  port: 80
