name: gateway-service

replicaCount: 1

image:
  repository: 879381276515.dkr.ecr.ap-northeast-2.amazonaws.com/aigungbu/service-images
  tag: 1c12dd2b6bed62fd32f2af96844313db7bfccf88
  pullPolicy: IfNotPresent

containerPort: 80

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: CONFIG_SERVER_URL
    value: http://config-service:8888
  - name: VAULT_URI
    value: VAULT_URI=http://vault.vault.svc.cluster.local:8200
  - name: VAULT_TOKEN
    value: myroot

service:
  type: ClusterIP
  port: 80
