name: gateway-service

replicaCount: 1

image:
  repository: 879381276515.dkr.ecr.ap-northeast-2.amazonaws.com/aigongbu/service-images
  tag: ec56fd29c6ac7ad8e8cc07d62bf6dbbede5c1984
  pullPolicy: IfNotPresent

containerPort: 80

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 384Mi

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: CONFIG_SERVER_URL
    value: http://config-service:8888
  - name: VAULT_URI
    value: http://vault.vault:8200
  - name: VAULT_TOKEN
    value: f6bxR0xz6auzfZJ1

service:
  type: ClusterIP
  port: 80
