name: gateway-service

replicaCount: 1

image:
  repository: 879381276515.dkr.ecr.ap-northeast-2.amazonaws.com/aigongbu/service-images
  tag: 42b3b6a619e34b9ca44a31695d09d14f7e5bda5c
  pullPolicy: IfNotPresent

containerPort: 80

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 384Mi

service:
  type: ClusterIP
  port: 80
