name: gateway-service

replicaCount: 1

image:
  repository: 879381276515.dkr.ecr.ap-northeast-2.amazonaws.com/aigongbu/service-images
  tag: 4fc7590ce37526bbd3fd646d1e9bb7cf2644b063
  pullPolicy: IfNotPresent

containerPort: 80

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 384Mi

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev

service:
  type: ClusterIP
  port: 80
